version: ""

formatter: markdown table

name: terraform-aws-config-rules

content: |-
  # terraform-aws-config-rules

  GitHub: [StratusGrid/terraform-aws-config-rules](https://github.com/StratusGrid/terraform-aws-config-rules)

  AWS Config rules module to put in standard policies
  
  ## Example Single Region Configuration:
  ```hcl
  {{ include "examples/single-region/example1.tfnot" }}
  ```
  ---
  ## Example Multi Region Configuration:
  ```hcl
  {{ include "examples/multi-region/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
